/*
 * 星云 SpringDoc API
 * 星云 SpringDoc Application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.cloudcharts.xingyun.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PageInfoObject
 */
public class PageInfoObjectTest {
    private final PageInfoObject model = new PageInfoObject();

    /**
     * Model tests for PageInfoObject
     */
    @Test
    public void testPageInfoObject() {
        // TODO: test PageInfoObject
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property '_list'
     */
    @Test
    public void _listTest() {
        // TODO: test _list
    }

    /**
     * Test the property 'pageNum'
     */
    @Test
    public void pageNumTest() {
        // TODO: test pageNum
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'startRow'
     */
    @Test
    public void startRowTest() {
        // TODO: test startRow
    }

    /**
     * Test the property 'endRow'
     */
    @Test
    public void endRowTest() {
        // TODO: test endRow
    }

    /**
     * Test the property 'pages'
     */
    @Test
    public void pagesTest() {
        // TODO: test pages
    }

    /**
     * Test the property 'prePage'
     */
    @Test
    public void prePageTest() {
        // TODO: test prePage
    }

    /**
     * Test the property 'nextPage'
     */
    @Test
    public void nextPageTest() {
        // TODO: test nextPage
    }

    /**
     * Test the property 'isFirstPage'
     */
    @Test
    public void isFirstPageTest() {
        // TODO: test isFirstPage
    }

    /**
     * Test the property 'isLastPage'
     */
    @Test
    public void isLastPageTest() {
        // TODO: test isLastPage
    }

    /**
     * Test the property 'hasPreviousPage'
     */
    @Test
    public void hasPreviousPageTest() {
        // TODO: test hasPreviousPage
    }

    /**
     * Test the property 'hasNextPage'
     */
    @Test
    public void hasNextPageTest() {
        // TODO: test hasNextPage
    }

    /**
     * Test the property 'navigatePages'
     */
    @Test
    public void navigatePagesTest() {
        // TODO: test navigatePages
    }

    /**
     * Test the property 'navigatepageNums'
     */
    @Test
    public void navigatepageNumsTest() {
        // TODO: test navigatepageNums
    }

    /**
     * Test the property 'navigateFirstPage'
     */
    @Test
    public void navigateFirstPageTest() {
        // TODO: test navigateFirstPage
    }

    /**
     * Test the property 'navigateLastPage'
     */
    @Test
    public void navigateLastPageTest() {
        // TODO: test navigateLastPage
    }

}
