/*
 * 星云 SpringDoc API
 * 星云 SpringDoc Application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.cloudcharts.xingyun.client.model;

import cn.cloudcharts.xingyun.client.model.Database;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RDatabase
 */
public class RDatabaseTest {
    private final RDatabase model = new RDatabase();

    /**
     * Model tests for RDatabase
     */
    @Test
    public void testRDatabase() {
        // TODO: test RDatabase
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'msg'
     */
    @Test
    public void msgTest() {
        // TODO: test msg
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'executeTime'
     */
    @Test
    public void executeTimeTest() {
        // TODO: test executeTime
    }

    /**
     * Test the property 'exception'
     */
    @Test
    public void exceptionTest() {
        // TODO: test exception
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

}
