/*
 * 星云 SpringDoc API
 * 星云 SpringDoc Application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.cloudcharts.xingyun.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SqlDTO
 */
public class SqlDTOTest {
    private final SqlDTO model = new SqlDTO();

    /**
     * Model tests for SqlDTO
     */
    @Test
    public void testSqlDTO() {
        // TODO: test SqlDTO
    }

    /**
     * Test the property 'statement'
     */
    @Test
    public void statementTest() {
        // TODO: test statement
    }

    /**
     * Test the property 'databaseId'
     */
    @Test
    public void databaseIdTest() {
        // TODO: test databaseId
    }

    /**
     * Test the property 'maxRowNum'
     */
    @Test
    public void maxRowNumTest() {
        // TODO: test maxRowNum
    }

}
