/*
 * 星云 SpringDoc API
 * 星云 SpringDoc Application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.cloudcharts.xingyun.client.model;

import java.util.Objects;
import java.util.Arrays;
import cn.cloudcharts.xingyun.client.model.DriverConfigPO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import cn.cloudcharts.xingyun.client.JSON;

/**
 * Database
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T11:49:41.855+08:00[Asia/Shanghai]")
public class Database {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  private Integer tenantId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_GROUP_NAME = "groupName";
  @SerializedName(SERIALIZED_NAME_GROUP_NAME)
  private String groupName;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_IP = "ip";
  @SerializedName(SERIALIZED_NAME_IP)
  private String ip;

  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  private Integer port;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  private String username;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public static final String SERIALIZED_NAME_NOTE = "note";
  @SerializedName(SERIALIZED_NAME_NOTE)
  private String note;

  public static final String SERIALIZED_NAME_FLINK_CONFIG = "flinkConfig";
  @SerializedName(SERIALIZED_NAME_FLINK_CONFIG)
  private String flinkConfig;

  public static final String SERIALIZED_NAME_FLINK_TEMPLATE = "flinkTemplate";
  @SerializedName(SERIALIZED_NAME_FLINK_TEMPLATE)
  private String flinkTemplate;

  public static final String SERIALIZED_NAME_DB_VERSION = "dbVersion";
  @SerializedName(SERIALIZED_NAME_DB_VERSION)
  private String dbVersion;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private Boolean status;

  public static final String SERIALIZED_NAME_HEALTH_TIME = "healthTime";
  @SerializedName(SERIALIZED_NAME_HEALTH_TIME)
  private OffsetDateTime healthTime;

  public static final String SERIALIZED_NAME_HEARTBEAT_TIME = "heartbeatTime";
  @SerializedName(SERIALIZED_NAME_HEARTBEAT_TIME)
  private OffsetDateTime heartbeatTime;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled;

  public static final String SERIALIZED_NAME_CREATE_TIME = "createTime";
  @SerializedName(SERIALIZED_NAME_CREATE_TIME)
  private OffsetDateTime createTime;

  public static final String SERIALIZED_NAME_UPDATE_TIME = "updateTime";
  @SerializedName(SERIALIZED_NAME_UPDATE_TIME)
  private OffsetDateTime updateTime;

  public static final String SERIALIZED_NAME_DRIVER_CONFIG = "driverConfig";
  @SerializedName(SERIALIZED_NAME_DRIVER_CONFIG)
  private DriverConfigPO driverConfig;

  public Database() {
  }

  public Database id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public Database tenantId(Integer tenantId) {
    
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @javax.annotation.Nullable
  public Integer getTenantId() {
    return tenantId;
  }


  public void setTenantId(Integer tenantId) {
    this.tenantId = tenantId;
  }


  public Database name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Database groupName(String groupName) {
    
    this.groupName = groupName;
    return this;
  }

   /**
   * Get groupName
   * @return groupName
  **/
  @javax.annotation.Nullable
  public String getGroupName() {
    return groupName;
  }


  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }


  public Database type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public Database ip(String ip) {
    
    this.ip = ip;
    return this;
  }

   /**
   * Get ip
   * @return ip
  **/
  @javax.annotation.Nullable
  public String getIp() {
    return ip;
  }


  public void setIp(String ip) {
    this.ip = ip;
  }


  public Database port(Integer port) {
    
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @javax.annotation.Nullable
  public Integer getPort() {
    return port;
  }


  public void setPort(Integer port) {
    this.port = port;
  }


  public Database url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public Database username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @javax.annotation.Nullable
  public String getUsername() {
    return username;
  }


  public void setUsername(String username) {
    this.username = username;
  }


  public Database password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @javax.annotation.Nullable
  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  public Database note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @javax.annotation.Nullable
  public String getNote() {
    return note;
  }


  public void setNote(String note) {
    this.note = note;
  }


  public Database flinkConfig(String flinkConfig) {
    
    this.flinkConfig = flinkConfig;
    return this;
  }

   /**
   * Get flinkConfig
   * @return flinkConfig
  **/
  @javax.annotation.Nullable
  public String getFlinkConfig() {
    return flinkConfig;
  }


  public void setFlinkConfig(String flinkConfig) {
    this.flinkConfig = flinkConfig;
  }


  public Database flinkTemplate(String flinkTemplate) {
    
    this.flinkTemplate = flinkTemplate;
    return this;
  }

   /**
   * Get flinkTemplate
   * @return flinkTemplate
  **/
  @javax.annotation.Nullable
  public String getFlinkTemplate() {
    return flinkTemplate;
  }


  public void setFlinkTemplate(String flinkTemplate) {
    this.flinkTemplate = flinkTemplate;
  }


  public Database dbVersion(String dbVersion) {
    
    this.dbVersion = dbVersion;
    return this;
  }

   /**
   * Get dbVersion
   * @return dbVersion
  **/
  @javax.annotation.Nullable
  public String getDbVersion() {
    return dbVersion;
  }


  public void setDbVersion(String dbVersion) {
    this.dbVersion = dbVersion;
  }


  public Database status(Boolean status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  public Boolean getStatus() {
    return status;
  }


  public void setStatus(Boolean status) {
    this.status = status;
  }


  public Database healthTime(OffsetDateTime healthTime) {
    
    this.healthTime = healthTime;
    return this;
  }

   /**
   * Get healthTime
   * @return healthTime
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getHealthTime() {
    return healthTime;
  }


  public void setHealthTime(OffsetDateTime healthTime) {
    this.healthTime = healthTime;
  }


  public Database heartbeatTime(OffsetDateTime heartbeatTime) {
    
    this.heartbeatTime = heartbeatTime;
    return this;
  }

   /**
   * Get heartbeatTime
   * @return heartbeatTime
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getHeartbeatTime() {
    return heartbeatTime;
  }


  public void setHeartbeatTime(OffsetDateTime heartbeatTime) {
    this.heartbeatTime = heartbeatTime;
  }


  public Database enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public Database createTime(OffsetDateTime createTime) {
    
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getCreateTime() {
    return createTime;
  }


  public void setCreateTime(OffsetDateTime createTime) {
    this.createTime = createTime;
  }


  public Database updateTime(OffsetDateTime updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Get updateTime
   * @return updateTime
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getUpdateTime() {
    return updateTime;
  }


  public void setUpdateTime(OffsetDateTime updateTime) {
    this.updateTime = updateTime;
  }


  public Database driverConfig(DriverConfigPO driverConfig) {
    
    this.driverConfig = driverConfig;
    return this;
  }

   /**
   * Get driverConfig
   * @return driverConfig
  **/
  @javax.annotation.Nullable
  public DriverConfigPO getDriverConfig() {
    return driverConfig;
  }


  public void setDriverConfig(DriverConfigPO driverConfig) {
    this.driverConfig = driverConfig;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Database database = (Database) o;
    return Objects.equals(this.id, database.id) &&
        Objects.equals(this.tenantId, database.tenantId) &&
        Objects.equals(this.name, database.name) &&
        Objects.equals(this.groupName, database.groupName) &&
        Objects.equals(this.type, database.type) &&
        Objects.equals(this.ip, database.ip) &&
        Objects.equals(this.port, database.port) &&
        Objects.equals(this.url, database.url) &&
        Objects.equals(this.username, database.username) &&
        Objects.equals(this.password, database.password) &&
        Objects.equals(this.note, database.note) &&
        Objects.equals(this.flinkConfig, database.flinkConfig) &&
        Objects.equals(this.flinkTemplate, database.flinkTemplate) &&
        Objects.equals(this.dbVersion, database.dbVersion) &&
        Objects.equals(this.status, database.status) &&
        Objects.equals(this.healthTime, database.healthTime) &&
        Objects.equals(this.heartbeatTime, database.heartbeatTime) &&
        Objects.equals(this.enabled, database.enabled) &&
        Objects.equals(this.createTime, database.createTime) &&
        Objects.equals(this.updateTime, database.updateTime) &&
        Objects.equals(this.driverConfig, database.driverConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tenantId, name, groupName, type, ip, port, url, username, password, note, flinkConfig, flinkTemplate, dbVersion, status, healthTime, heartbeatTime, enabled, createTime, updateTime, driverConfig);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Database {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    flinkConfig: ").append(toIndentedString(flinkConfig)).append("\n");
    sb.append("    flinkTemplate: ").append(toIndentedString(flinkTemplate)).append("\n");
    sb.append("    dbVersion: ").append(toIndentedString(dbVersion)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    healthTime: ").append(toIndentedString(healthTime)).append("\n");
    sb.append("    heartbeatTime: ").append(toIndentedString(heartbeatTime)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    driverConfig: ").append(toIndentedString(driverConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("tenantId");
    openapiFields.add("name");
    openapiFields.add("groupName");
    openapiFields.add("type");
    openapiFields.add("ip");
    openapiFields.add("port");
    openapiFields.add("url");
    openapiFields.add("username");
    openapiFields.add("password");
    openapiFields.add("note");
    openapiFields.add("flinkConfig");
    openapiFields.add("flinkTemplate");
    openapiFields.add("dbVersion");
    openapiFields.add("status");
    openapiFields.add("healthTime");
    openapiFields.add("heartbeatTime");
    openapiFields.add("enabled");
    openapiFields.add("createTime");
    openapiFields.add("updateTime");
    openapiFields.add("driverConfig");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Database
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Database.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Database is not found in the empty JSON string", Database.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Database.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Database` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("groupName") != null && !jsonObj.get("groupName").isJsonNull()) && !jsonObj.get("groupName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `groupName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("groupName").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("ip") != null && !jsonObj.get("ip").isJsonNull()) && !jsonObj.get("ip").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ip` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ip").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if ((jsonObj.get("username") != null && !jsonObj.get("username").isJsonNull()) && !jsonObj.get("username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("username").toString()));
      }
      if ((jsonObj.get("password") != null && !jsonObj.get("password").isJsonNull()) && !jsonObj.get("password").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `password` to be a primitive type in the JSON string but got `%s`", jsonObj.get("password").toString()));
      }
      if ((jsonObj.get("note") != null && !jsonObj.get("note").isJsonNull()) && !jsonObj.get("note").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `note` to be a primitive type in the JSON string but got `%s`", jsonObj.get("note").toString()));
      }
      if ((jsonObj.get("flinkConfig") != null && !jsonObj.get("flinkConfig").isJsonNull()) && !jsonObj.get("flinkConfig").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `flinkConfig` to be a primitive type in the JSON string but got `%s`", jsonObj.get("flinkConfig").toString()));
      }
      if ((jsonObj.get("flinkTemplate") != null && !jsonObj.get("flinkTemplate").isJsonNull()) && !jsonObj.get("flinkTemplate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `flinkTemplate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("flinkTemplate").toString()));
      }
      if ((jsonObj.get("dbVersion") != null && !jsonObj.get("dbVersion").isJsonNull()) && !jsonObj.get("dbVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbVersion").toString()));
      }
      // validate the optional field `driverConfig`
      if (jsonObj.get("driverConfig") != null && !jsonObj.get("driverConfig").isJsonNull()) {
        DriverConfigPO.validateJsonObject(jsonObj.getAsJsonObject("driverConfig"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Database.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Database' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Database> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Database.class));

       return (TypeAdapter<T>) new TypeAdapter<Database>() {
           @Override
           public void write(JsonWriter out, Database value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Database read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Database given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Database
  * @throws IOException if the JSON string is invalid with respect to Database
  */
  public static Database fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Database.class);
  }

 /**
  * Convert an instance of Database to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

