/*
 * 星云 SpringDoc API
 * 星云 SpringDoc Application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.cloudcharts.xingyun.client.api;

import cn.cloudcharts.xingyun.client.ApiException;
import cn.cloudcharts.xingyun.client.model.DataBaseRequest;
import cn.cloudcharts.xingyun.client.model.Database;
import cn.cloudcharts.xingyun.client.model.R;
import cn.cloudcharts.xingyun.client.model.RDatabase;
import cn.cloudcharts.xingyun.client.model.RPageInfoObject;
import cn.cloudcharts.xingyun.client.model.RVoid;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DatabaseControllerApi
 */
@Disabled
public class DatabaseControllerApiTest {

    private final DatabaseControllerApi api = new DatabaseControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addTest() throws ApiException {
        Database database = null;
        R response = api.add(database);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void callListTest() throws ApiException {
        DataBaseRequest dataBaseRequest = null;
        RPageInfoObject response = api.callList(dataBaseRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOneByIdTest() throws ApiException {
        String id = null;
        RDatabase response = api.getOneById(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void saveOrUpdateTest() throws ApiException {
        Database database = null;
        RVoid response = api.saveOrUpdate(database);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void testConnectTest() throws ApiException {
        Database database = null;
        R response = api.testConnect(database);
        // TODO: test validations
    }

}
