/*
 * 星云 SpringDoc API
 * 星云 SpringDoc Application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.cloudcharts.xingyun.client.api;

import cn.cloudcharts.xingyun.client.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HelloControllerApi
 */
@Disabled
public class HelloControllerApiTest {

    private final HelloControllerApi api = new HelloControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void homeTest() throws ApiException {
        String response = api.home();
        // TODO: test validations
    }

}
